# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180117_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('eMail', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='number',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transport'),
        ),
    ]
